### ISSUE TITLE
ECCN for openvx

### ISSUE THREAD

**Issue by shridhargowda100** [KhronosGroup/OpenVX-Registry#42]
Hi, For documentation purpose and project release process we need the Export control classification number(ECCN) for openvx if it applies. Can you please let me know the ECCN ?

**Comment by oddhack** [comment]
Hi @shridhargowda100 . We would like to get some clarification, since an identical question was recently posted by another github user in https://github.com/KhronosGroup/OpenCL-Headers/issues/130, and both of you appear to be brand new github users. Can you clarify your reason for asking - e.g. is there perhaps a new documentation regime imposed by your company, industry, or country, or some other reason you need to know this? What company or project you are asking this on behalf of? And whether Khronos should expect this question to be extended to more of our specifications and related materials? Thanks.

**Comment by oddhack** [comment]
Closing due to lack of response.
